Fixes

diff --git a/make-openwrt/openwrt-files/different-files/khadas-vim1/rootfs/etc/board.d/10_vims_hw_eth_optimize b/make-openwrt/openwrt-files/different-files/khadas-vim1/rootfs/etc/board.d/10_vims_hw_eth_optimize
--- a/make-openwrt/openwrt-files/different-files/khadas-vim1/rootfs/etc/board.d/10_vims_hw_eth_optimize
+++ b/make-openwrt/openwrt-files/different-files/khadas-vim1/rootfs/etc/board.d/10_vims_hw_eth_optimize
@@ -10,8 +10,8 @@ IFACE=eth0
 
 [ -d /sys/class/net/$IFACE ] || {
 
-    echo "[w] dev $IFACE not found">&2
-    exit 1
+	echo "[w] dev $IFACE not found" >&2
+	exit 1
 
 }
 
@@ -22,24 +22,24 @@ IFACE=eth0
 #    CPU 2    0100         4
 #    CPU 3    1000         8
 
-# 
+#
 case "$SOC" in
-    *A311D*)
-#    echo "[i] optimize VIM3: $SOC">&2
-#    echo 2 > /proc/irq/6/smp_affinity
-    ifconfig $IFACE up
-    ;;
+*A311D*)
+	#    echo "[i] optimize VIM3: $SOC">&2
+	#    echo 2 > /proc/irq/6/smp_affinity
+	ifconfig $IFACE up
+	;;
 
-    *SM1*)
-#    echo "[i] optimize VIM3L: $SOC">&2
-#    echo 2 > /proc/irq/6/smp_affinity
-    ifconfig $IFACE up
-    ;;
-    
-    *)
-    echo "[i] optimize DEF: $SOC">&2
-#    echo 2 > /proc/irq/23/smp_affinity
+*SM1*)
+	#    echo "[i] optimize VIM3L: $SOC">&2
+	#    echo 2 > /proc/irq/6/smp_affinity
+	ifconfig $IFACE up
+	;;
 
-    ;;
+*)
+	echo "[i] optimize DEF: $SOC" >&2
+	#    echo 2 > /proc/irq/23/smp_affinity
+
+	;;
 
 esac
